### ISSUE TITLE
AVX2 instructions error

### ISSUE THREAD

**Issue by user84918342** [SimiaCryptus/tf-gpt-2#1]
When running a simple test (`System.out.println(t.generateText(100, "Testing this"));`)
I get following error: 
`21:49:01.030 [main] DEBUG com.simiacryptus.text.gpt2.GPT2Model - Reset Language Model State
21:49:01.077 [main] DEBUG com.simiacryptus.text.gpt2.GPT2Model - Eval 2215
2020-10-02 21:49:02.488283: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Exception in thread "main" java.lang.IllegalArgumentException: Invalid GraphDef
	at org.tensorflow.Graph.importGraphDef(Native Method)
	at org.tensorflow.Graph.importGraphDef(Graph.java:130)
	at org.tensorflow.Graph.importGraphDef(Graph.java:114)
	at com.simiacryptus.text.gpt2.GPT2Model.getSession(GPT2Model.java:213)
	at com.simiacryptus.text.gpt2.GPT2Model.eval(GPT2Model.java:96)
	at com.simiacryptus.text.gpt2.TextGenerator.generateText(TextGenerator.java:68)
	at Test.main(Test.java:6)
`

Here is the fix: https://appuals.com/fix-your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-use-avx2/

But I have no idea how to implement it in the java code.

**Comment by jramiromolina** [comment]
Same issue here
